### ISSUE TITLE
Java thread stuck at socket channel read in BeanstalkConnection.java

### ISSUE THREAD

**Issue by Srthk** [dustismo/TrendrrBeanstalk#23]
When our beanstalkd was hung, the connections got stuck and did not timeout. 
On checking BeanstalkConnection.java, the client should throw exception if there is nothing to read from buffer for 100 seconds. But that doesn't happen, as thread gets stuck at first read only

This line never gets executed -
`throw new BeanstalkDisconnectedException("OH Snap, nothing to read from the buffer for 100 seconds!");
`
Below was the jstack during this situation - 
`
java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
        - locked <0x00000000f8f391f0> (a java.lang.Object)
        at com.trendrr.beanstalk.BeanstalkConnection.readControlResponse(BeanstalkConnection.java:111)
        at com.trendrr.beanstalk.BeanstalkClient.useTube(BeanstalkClient.java:132)
        at com.trendrr.beanstalk.BeanstalkClient.init(BeanstalkClient.java:119)
        at com.trendrr.beanstalk.BeanstalkClient.put(BeanstalkClient.java:231)
        at in.exotel.jqix.beanstalk.BeanStalkQueue.enqueue(BeanStalkQueue.java:145)
        - locked <0x00000000f8f39490> (a in.exotel.jqix.beanstalk.BeanStalkQueue)
        at in.exotel.jqix.beanstalk.BeanStalkQueue.enqueue(BeanStalkQueue.java:102)
        - locked <0x00000000f8f39490> (a in.exotel.jqix.beanstalk.BeanStalkQueue)
        at in.exotel.billix.NewBillixClient.sendCommand(NewBillixClient.java:190)
        - locked <0x00000000f8f394d8> (a in.exotel.billix.NewBillixClient)
        at in.exotel.billix.NewBillixClient.addSmsEvent(NewBillixClient.java:267)
        at in.exotel.ceramix.BillixHelper.addSmsEventToBillix(BillixHelper.java:56)
        at in.exotel.ceramix.SmsStatusUpdater.handleSmsStatusUpdate(SmsStatusUpdater.java:348)
        at in.exotel.ceramix.SmsStatusUpdater.handleSmsSendResponse(SmsStatusUpdater.java:105)
        at in.exotel.ceramix.SmsStatusUpdateJob.call(SmsStatusUpdateJob.java:74)
        at in.exotel.ceramix.SmsStatusUpdateJob.call(SmsStatusUpdateJob.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
`
Not sure if this has happened to others. But there should be some kind of socket read timeout or something. So that threads don't get stuck indefinitely.

**Comment by sadwxqezc** [comment]
I have the same problem

**Comment by Srthk** [comment]
Have fixed this by using socket timeout while initialising connection. Pull Request - #24
